# This is a basic workflow to help you get started with Actions

name: mainworkflow

# Controls when the action will run. 
on:
  pull_request:
    branches: [main]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10,12,14]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Random job
        run: Am a Random job
  deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - run: echo First jobs passed


